### ISSUE TITLE
Design doc: specifying HCL and Terraform variables

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-testing#12]
Acceptance tests require fully specified Terraform configuration. Unless these config files are specified as templates, we also need a way to specify the values for variables.

This is a large design area with many tradeoffs to consider. The design document may want to answer some or all of the following questions:

- How do we want to specify HCL for the test?
  - HCL files on disk?
  - HCL template files on disk?
  - Hardcoded Go strings/functions?
 
- For test HCL files on disk, how strict will we be about their name and location?
  - Must be located in ./testdata?
  - Must be named 1.tf, 2.tf, etc?
- Can test HCL files also serve as example configs in provider docs?
  - Yes
  - No
  - Not always, but we provide a way to differentiate between those that can and those that can’t
- How do we want to generate random values for the HCL in the test?
  - Terraform variables
  - Source code transformation at runtime
- How do we want to specify Terraform variables for the test?
  - Var files that live alongside HCL files on disk?
  - Map of vars specified in test code?

**Comment by bflad** [comment]
We wound up internally RFC'ing and releasing the following functionality here:

- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing/config
- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing/helper/resource#TestStep.ConfigDirectory
- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing/helper/resource#TestStep.ConfigFile
- https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing/helper/resource#TestStep.ConfigVariables

🚀
