### ISSUE TITLE
Review results of user research survey

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-testing#2]
Needs #1 

Subject to the [research plan](https://docs.google.com/document/d/1kmh9lAToApsrlgcDNgCclnHr_H61EK0eRrCsYYtFyM0/edit), we may do this on a set date, or once we have received a certain number of responses.

The results of the survey should be reviewed and processed such that they can inform terraform-plugin-testing design decisions. This may involve team design discussions, creating issues, and creating or modifying design documents.

**Comment by bflad** [comment]
Refer to https://github.com/hashicorp/terraform-plugin-testing/issues/1#issuecomment-1529919842
