### ISSUE TITLE
`Failed to marshal plan to json: value is not known` on `terraform-plugin-testing@v1.6.0`

### ISSUE THREAD

**Issue by SuperBuker** [hashicorp/terraform-plugin-testing#262]
### terraform-plugin-testing version

```
1.6.0
```

### Relevant provider source code

The issue only affects the DDNSKey resource, as due to API limitations, it's not possible to retrieve the currently stored key, but only check if the target one is valid. If it's not, setting a `types.StringUnknown()` in the current state triggers a resource update.

#### Schema
```go
resp.Schema = schema.Schema{
	Description:         "DDNS update key",
	MarkdownDescription: "DDNS update key",
	Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:            true,
			Description:         "dns.he.net ddns key id",
			MarkdownDescription: "dns.he.net ddns key id",
		},
		"domain": schema.StringAttribute{
			Required:            true,
			Description:         "dns.he.net ddns key domain",
			MarkdownDescription: "dns.he.net ddns key domain",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"zone_id": schema.Int64Attribute{
			Required:            true,
			Description:         "dns.he.net zone id",
			MarkdownDescription: "dns.he.net zone id",
			PlanModifiers: []planmodifier.Int64{
				int64planmodifier.RequiresReplace(),
			},
		},
		"key": schema.StringAttribute{
			Required:            true,
			Sensitive:           true,
			Description:         "dns.he.net ddns key secret",
			MarkdownDescription: "dns.he.net ddns key secret",
		},
	},
}
```
#### Resource read function
```go
// Read refreshes the Terraform state with the latest data.
func (dk ddnsKey) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ddnsKeyModel

	// Retrieve values from state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Check if the state key is still valid, remove otherwhise
	ok, err := dk.client.DDNS().CheckAuth(ctx, state.Domain.ValueString(), state.Key.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to validate DDNS key",
			err.Error(),
		)
		return
	} else if !ok {
		// Current key is invalid, removing from state
		state.Key = types.StringUnknown()
	}

	// Set state
	diags = resp.State.Set(ctx, state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}
```

### Terraform Configuration Files

During the test, at the beginning of the step 2, the DDNSKey is manually updated to trigger the record update dure to an unknown state.

```go
func TestAccDDNSKey(t *testing.T) {
	t.Parallel()

	domains := Zone.RandSubs("example-%04d", 10000, 2)
	domainInit := domains[0]
	domainUpdate := domains[1]

	password := randStringBytesMaskImprSrcSB(16)

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: test_utils.TestAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			// Validate defaults
			{
				Config: ProviderConfig +
					fmt.Sprintf(`resource "dns-he-net_ddnskey" "ddnskey" {
					zone_id = %d
					domain = %q
					key = %q
				}`, Zone.ID, domainInit, password),
				Check: resource.ComposeAggregateTestCheckFunc(
					// Verify record attibutes
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "id", domainInit),
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "domain", domainInit),
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "zone_id", toString(Zone.ID)),
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "key", password),
				),
			},
			// Update and Read testing
			{
				PreConfig: func() {
					// Force the ddns key to be updated externally
					authObj, err := Account.Auth(auth.Simple)
					require.NoError(t, err)

					cli, err := client.NewClient(context.Background(), authObj, logging.NewZerolog(zerolog.DebugLevel, false))
					require.NoError(t, err)

					assert.Equal(t, Account.ID, cli.GetAccount())

					// Makes auth fail when validating the expected key, triggering an update
					anotherPassword := randStringBytesMaskImprSrcSB(16)

					ddnsKey := models.DDNSKey{
						Domain: domainInit,
						ZoneID: Zone.ID,
						Key:    anotherPassword,
					}

					_, err = cli.SetDDNSKey(context.Background(), ddnsKey)
					require.NoError(t, err)
				},
				Config: ProviderConfig +
					fmt.Sprintf(`resource "dns-he-net_ddnskey" "ddnskey" {
					zone_id = %d
					domain = %q
					key = %q
				}`, Zone.ID, domainInit, password),
				Check: resource.ComposeAggregateTestCheckFunc(
					// Verify record attibutes
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "id", domainInit),
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "domain", domainInit),
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "zone_id", toString(Zone.ID)),
					resource.TestCheckResourceAttr("dns-he-net_ddnskey.ddnskey", "key", password),
				),
			},
		},
	})
}
```

### Expected Behavior

With **v1.5.1**

```shell
$ go test -run ^TestAccDDNSKey$ github.com/SuperBuker/terraform-provider-dns-he-net/internal/resources -v -cover

=== RUN   TestAccDDNSKey
=== PAUSE TestAccDDNSKey
=== CONT  TestAccDDNSKey
2024-01-05T13:09:38Z INF api message status="Successfully generated key for dynamic record example-1500.domain.tld."
--- PASS: TestAccDDNSKey (23.23s)
PASS
coverage: 7.2% of statements
ok  	github.com/SuperBuker/terraform-provider-dns-he-net/internal/resources	25.193s	coverage: 7.2% of statements
```

### Actual Behavior

With **v1.6.0**

```shell
$ go test -run ^TestAccDDNSKey$ github.com/SuperBuker/terraform-provider-dns-he-net/internal/resources -v -cover

=== RUN   TestAccDDNSKey
=== PAUSE TestAccDDNSKey
=== CONT  TestAccDDNSKey
2024-01-05T13:28:00Z INF api message status="Successfully generated key for dynamic record example-7291.domain.tld."
    /workspace/dns-he-net/internal/resources/ddns_key_test.go:28: Step 2/3 error: Error running pre-apply plan: error retrieving formatted plan output: exit status 1
        Failed to marshal plan to json: value is not known
--- FAIL: TestAccDDNSKey (6.18s)
FAIL
coverage: 6.6% of statements
FAIL	github.com/SuperBuker/terraform-provider-dns-he-net/internal/resources	7.965s
```

**Comment by bflad** [comment]
Hi @SuperBuker 👋 Thank you for raising this and sorry you are running into trouble here.

What I think is happening here is that nothing (Terraform core or terraform-plugin-framework) is catching the setting of an unknown value into the state from the `Read` method to raise an explicit error. I don't believe unknown values are ever valid be saved into a resource instance state. I notice we do not explicitly call this in the [framework resource read documentation](https://developer.hashicorp.com/terraform/plugin/framework/resources/read), nor the [Resource Instance Change Lifecycle](https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md) `ReadResource` RPC (only `ApplyResourceChange`). You may want to verify what happens for practitioners in this real-world situation outside the acceptance testing, e.g.

- Create a regular Terraform configuration and `terraform apply`
- Update the remote system, similar to the `PreConfig` logic
- Run `terraform plan` and/or `terraform apply`

It may unintentionally work okay today, but the behavior might not be protected by Terraform's compatibility promises and I do want to check with the Terraform maintainers about this.

Setting the attribute value to a known, but "invalid" value might achieve the same behavior, where Terraform should show the difference of prior state to the configuration and plan for the resource update. Since the attribute is marked as sensitive anyways, the value difference should be inconsequential.

As for why this changed between terraform-plugin-testing v1.5.1 and v1.6.0 is that there is no longer an implicit `terraform refresh` command being run at the beginning of each `Config`-based `TestStep`. This matches Terraform's documented recommendations and general practitioner behavior to run `terraform plan` with its default refresh behavior instead. Theoretically, any practitioner running `terraform plan` after the remote system update might see a similar error.

**Comment by bflad** [comment]
Hi again, @SuperBuker. I just discussed this with some of the Terraform maintainers and the opinion is that this setting of  unknown values during `ReadResource` should never be allowed. We will get the various documentation updated and I will be creating an upstream issue to see if Terraform can raise a more explicit error before the errant state is stored. We could also consider having terraform-plugin-framework also raising its own error, so this is covered for environments using prior versions of Terraform to that potential change.

**Comment by bflad** [comment]
It's also worth mentioning that setting the value to null, e.g. `types.StringNull()`, should be a good enough value for refreshing in your use case. As the attribute in question is already marked as required, it means it is already being validated that the configuration value is not null, so there will always be a difference between null and whatever configuration value is given.

**Comment by SuperBuker** [comment]
Hi @bflad, I've verified the current behaviour and the cli returns `Failed to marshal plan to json: value is not known` instead of displaying the terraform plan. After replacing the value with `types.StringNull()` the plan is correctly printed and the provider behaviour remains the expected.

On my side, the issue can be closed. Thanks a lot for your help.

**Comment by bflad** [comment]
Thanks so much, @SuperBuker 👍 

Created the following issues for followup:

- https://github.com/hashicorp/terraform-plugin-framework/issues/902
- https://github.com/hashicorp/terraform/issues/34502
- https://github.com/hashicorp/terraform/issues/34503 (similar issue with `UpgradeResourceState`)
