### ISSUE TITLE
Modify detection of provider blocks in configuration

### ISSUE THREAD

**Issue by bendbennett** [hashicorp/terraform-plugin-testing#264]
### terraform-plugin-testing version
```
v1.6.0
```

### Relevant provider source code

N/A

### Terraform Configuration Files

The following are all allowed `provider` block declarations from the perspective of `terraform validate`.

```tf
provider"random"{}
```
```tf
provider "random"{}
```
```tf
provider random{}
```

### Expected Behavior
Using the `provider` block configurations supplied should result in successfully executing tests.

### Actual Behavior
The following error is raised:

```shell
        Error: Duplicate provider configuration
        
          on terraform_plugin_test.tf line 13:
          13: provider"random"{}
        
        A default (non-aliased) provider configuration for "random" was already given
        at terraform_plugin_test.tf:11,1-18. If multiple configurations are required,
        set the "alias" argument for alternative configurations.
    testing_new.go:80: Error retrieving state, there may be dangling resources: exit status 1
```

### Steps to Reproduce
Run an acceptance test with a `provider` block configuration that uses the quoting and /or spacing described in `Terraform Configuration Files`.

**Comment by bflad** [comment]
I wonder if we should submit something upstream for `provider"random"{}` -- its probably fine for us to support the lack of whitespace after the provider block label, but the label-without-prior-whitespace feels very 😬 to me personally.

**Comment by bendbennett** [comment]
There's actually no usage of `provider"random"{}` in the `random` provider. @austinvalle uncovered that these various forms of provider block declaration are all legitimate terraform configuration, so I thought it might be best to have the detection of these forms of declaration be taken into account in case they caused the errors described.

**Comment by bflad** [comment]
I have no issues with implementing the unquoted and whitespace missing after label cases (e.g. `provider "LABEL"{`), but I'm asking if we should submit an issue to https://github.com/hashicorp/terraform/issues to consider having `terraform validate` raise an error if it encounters `provider"LABEL"{` without the whitespace before the label. It may be valid in HCL for whatever reason, but seems like an awkward Terraform configuration style to support.

**Comment by austinvalle** [comment]
drive-by - 🚗 -  `terraform fmt` will add those whitespaces in (which our addition of config files and directories will make it easier to take advantage of 🥳 )

![image](https://github.com/hashicorp/terraform-plugin-testing/assets/8650838/b7550788-b0ef-42ed-b20b-4e8ef01aeadc)

Looking at the [`validate`](https://developer.hashicorp.com/terraform/cli/commands/validate) command docs, they emphasize that the config is only checked for syntactic correctness:
> _Validate runs checks that verify whether a configuration is syntactically valid and internally consistent, regardless of any provided variables or existing state._

I'd imagine based on how it's described that they'd be unlikely to also check formatting during that command.

Maybe we could add a test warning if we detect that `terraform fmt -check` says the formatting is wonky, since it's possible and probable that provider developers will be just using Go strings for their config. Although that might open another can of worms 😆

**Comment by austinvalle** [comment]
At the very least, it's probably worth documenting (if we haven't already) that we dynamically add terraform configuration to their test configs if needed.

**Comment by bendbennett** [comment]
> I have no issues with implementing the unquoted and whitespace missing after label cases (e.g. `provider "LABEL"{`), but I'm asking if we should submit an issue to https://github.com/hashicorp/terraform/issues to consider having `terraform validate` raise an error if it encounters `provider"LABEL"{` without the whitespace before the label. It may be valid in HCL for whatever reason, but seems like an awkward Terraform configuration style to support.

Ooops. Apologies, I completely misunderstood what you were getting at here. I've opened an issue for [Consider having terraform validate raise an error if provider block defined without whitespace](https://github.com/hashicorp/terraform/issues/34507#top).

**Comment by bendbennett** [comment]
> drive-by - 🚗 - `terraform fmt` will add those whitespaces in (which our addition of config files and directories will make it easier to take advantage of 🥳 )
> 
> ![image](https://private-user-images.githubusercontent.com/8650838/295027670-b7550788-b0ef-42ed-b20b-4e8ef01aeadc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODIzMDIsIm5iZiI6MTcwNDc4MjAwMiwicGF0aCI6Ii84NjUwODM4LzI5NTAyNzY3MC1iNzU1MDc4OC1iMGVmLTQyZWQtYjIwYi00ZThlZjAxYWVhZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMDYzMzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYxNTczMWRiZGE1ZTdlMGVlZmYxNGZlOTY1NjM0OWI5NWJlMzRkOGU5ZGQ4YWNkM2Y3MmMyMGUxZGI1NDk0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9b28ey7Lnv8X3nZPfiAfFoHs7tLpiKzo-Rl93nLbK2M)
> 
> Looking at the [`validate`](https://developer.hashicorp.com/terraform/cli/commands/validate) command docs, they emphasize that the config is only checked for syntactic correctness:
> 
> > _Validate runs checks that verify whether a configuration is syntactically valid and internally consistent, regardless of any provided variables or existing state._
> 
> I'd imagine based on how it's described that they'd be unlikely to also check formatting during that command.
> 
> Maybe we could add a test warning if we detect that `terraform fmt -check` says the formatting is wonky, since it's possible and probable that provider developers will be just using Go strings for their config. Although that might open another can of worms 😆

Have added an issue for [Consider running terraform validate against supplied configuration](https://github.com/hashicorp/terraform-plugin-testing/issues/270#top) to track this.
