### ISSUE TITLE
Setup Repository to Release Versioned Documentation to developer.hashicorp.com/plugin

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-testing#27]
### Does this documentation exist?

* [x] This is new documentation
* [ ] This is an enhancement to existing documentation

### Where would you expect to find this documentation?

* [x] On terraform.io
* [ ] In the GoDoc for this module
* [ ] In this repo as a markdown file
* [ ] Somewhere else

#### Details

This repository needs to be hooked up to the marketing content workflows for developer.hashicorp.com/plugin/XXX when its released, similar to other terraform-plugin-* repositories.

**Comment by SBGoods** [comment]
Repo is now the remote source for https://developer.hashicorp.com/terraform/plugin/testing and website is live.
