### ISSUE TITLE
terraform-plugin-sdk/v2/helper/resource Migration Documentation

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-testing#28]
### Does this documentation exist?

* [x] This is new documentation
* [ ] This is an enhancement to existing documentation

### Where would you expect to find this documentation?

* [x] On terraform.io
* [ ] In the GoDoc for this module
* [ ] In this repo as a markdown file
* [ ] Somewhere else

#### Details

Folks that are currently using terraform-plugin-sdk for provider testing will need documentation for how to migrate to this new Go module. There should be information on what they need to do, e.g.

- Change Go import statements in `*_test.go` files:
    - `github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest` to `github.com/hashicorp/terraform-plugin-testing/helper/acctest`
    - `github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource` to `github.com/hashicorp/terraform-plugin-testing/helper/resource`
- `go get github.com/hashicorp/terraform-plugin-testing@v1.0.0`
- `go mod tidy`
- Verify everything is working as expected.

It may also be worth considering putting informational boxes on each of the sdk website testing documentation pages to point at the migration or new documentation.

**Comment by SBGoods** [comment]
Migration docs are now available at https://developer.hashicorp.com/terraform/plugin/testing/migrating/
