### ISSUE TITLE
Document debugging of acceptance tests

### ISSUE THREAD

**Issue by azrdev** [hashicorp/terraform-plugin-testing#353]
### Does this documentation exist?

* [x] This is new documentation
* [ ] This is an enhancement to existing documentation

### Where would you expect to find this documentation?

* [x] On terraform.io
* [ ] In the GoDoc for this module
* [x] In this repo as a markdown file
* [ ] Somewhere else

#### Details

https://developer.hashicorp.com/terraform/plugin/framework/acctests describes how to write and run (`TF_ACC=1`) acceptance tests for terraform providers using the plugin framework.

https://developer.hashicorp.com/terraform/plugin/framework/debugging and https://developer.hashicorp.com/terraform/plugin/debugging#starting-a-provider-in-debug-mode describe how to start a provider server in a debugger (e.g. delve), and export its address using `TF_REATTACH_PROVIDERS` to any terraform commands run afterwards, enabling debugger support for the provider code.

I cannot find how to do both: run an acceptance test with `TF_ACC=1 TF_DEBUG=INFO  go test -v -run MyResourceCRUD .`   and get debugger support (e.g. breakpoints) in the provider code.

#### Extras

With `TF_LOG=TRACE` I can see multiple debug statements "Setting Terraform CLI reattach configuration", but apparently these are triggered by the provider instantiantion by the acceptance test driver (e.g. with `ProtoV6ProviderFactories` somewhere in the call stack), and I see no option to override.

### References

- https://discuss.hashicorp.com/t/tf-reattach-providers-appears-ignored/16912/4
- https://hashicorp.github.io/terraform-provider-aws/debugging/#use-visual-studio-code-debugging

**Comment by azrdev** [comment]
Apparently debugging just works™ running the test methods from within vscode, given the launch.json from here https://hashicorp.github.io/terraform-provider-aws/debugging/#use-visual-studio-code-debugging

Not sure what went wrong when first trying it.

Caveat: `env` and `envFile` seem to be ignored in my case (vscode on windows, running/debugging in WSL2), had to set my auth environment variables via `.vscode/settings.json` (`go.testEnvFile`)

**Comment by austinvalle** [comment]
Hey @azrdev 👋🏻, looks like you resolved your issue so I'm going to close this out.

I think what's out there should be sufficient, although if you have specific doc suggestions feel free to point them out. Any way that you get the `TF_ACC` environment variable populated in your test runner should work fine. Personally, I use VSCode and have my global user settings with `go.testEnvVars` like:
```jsonc
{
  // .. settings.json
  "go.testEnvVars": {
    "TF_ACC_TERRAFORM_PATH": "/Users/austin.valle/go/bin/terraform",
    "TF_LOG": "TRACE",
    "TF_ACC": "1",
  }
}
```

Although, most provider test debugging I'm doing is with providers that don't need credentials, so `go.testEnvFile` is also appropriate. I'd imagine using a project/workspace `settings.json` would lean towards using an env file, where you could define more "global" env variables in your user `settings.json`.
