### ISSUE TITLE
Develop research plan for in-depth research phase and contact participants

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-testing#4]
Needs #2, #3

The first phase of the test framework research project involves a widely distributed survey - see #1 and the [research plan](https://docs.google.com/document/d/1kmh9lAToApsrlgcDNgCclnHr_H61EK0eRrCsYYtFyM0/edit) for that phase.

After the first phase is completed, we begin the second phase, in which we use the participant pool we have developed and the feedback we have gathered from the first phase to conduct more in-depth research.

This research may involve 1:1 or small group **interviews**, **screensharing**, **site visits**, and other high-touch approaches to answer both focused and open-ended research questions.

 - [ ] Approach UXR team to determine process for user research project development
 - [ ] Draft research plan
 - [ ] SDK team review of research plan
 - [ ] Invite participants
     - [ ] Email open-source participants
     - [ ] Work with Chris Griggs to contact partner participants

Relevant background documents:
[HashiCorp UXR Playbook](https://docs.google.com/document/d/1xJma0TLXqhQJ44jgiYxh6sOix7ihi-ZKak4t01QETLo/edit#heading=h.b3jmdrrt17sf)

**Comment by bflad** [comment]
The Product organization has been owning and running 1:1 sessions with partner developers, etc. Those efforts are being tracked internally.
