### ISSUE TITLE
Core FR: Check that only an 'update' occurred in a test

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-plugin-testing#61]
In https://github.com/hashicorp/terraform/pull/15101 and https://github.com/hashicorp/terraform/pull/15102, it was discovered that tests that we thought were testing update were actually just doing a destroy and recreate. It would be great to have another option in `TestStep` that would confirm that no resources were destroyed or created in a step, only updated. In this particular scenario, if the test had been written correctly, it would have caught the bug leading to https://github.com/hashicorp/terraform/issues/15056 potentially before it was caught by a user.

**Comment by austinvalle** [comment]
Hello longtime subscribers of this issue 👋🏻 ,

We've recently released [Plan Checks](https://developer.hashicorp.com/terraform/plugin/testing/acceptance-tests/plan-checks) with [`terraform-plugin-testing v1.2.0`](https://github.com/hashicorp/terraform-plugin-testing/releases/tag/v1.2.0) and more specifically, [`plancheck.ExpectResourceAction`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-testing@v1.2.0/plancheck#ExpectResourceAction) that should satisfy the original feature request in this issue.

https://developer.hashicorp.com/terraform/plugin/testing/acceptance-tests/plan-checks#examples-using-plancheck-expectresourceaction

There is an example of how to use this plancheck in the linked documentation on the developer portal, but please [open a new issue](https://github.com/hashicorp/terraform-plugin-testing/issues) if you run into problems, or open a post on our [discuss board](https://discuss.hashicorp.com/c/terraform-providers/31) for other questions.
