### ISSUE TITLE
Acceptance testing: Ability to prevent a resource being deleted at the end of a `TestCase`

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-testing#85]
### SDK version

```console
% go list -m github.com/hashicorp/terraform-plugin-sdk/...
github.com/hashicorp/terraform-plugin-sdk/v2 v2.24.1
```

### Use-cases

Acceptance tests for https://github.com/hashicorp/terraform-provider-aws/pull/26274 need to manipulate an active [AWS Direct Connect connection](https://docs.aws.amazon.com/directconnect/latest/UserGuide/WorkingWithConnections.html). Activating a newly created Direct Connect connection requires manual intervention at a physical location, so creating the `aws_dx_connection` and waiting for it to become active in a `TestStep` is not feasible.
Using the [`TestStep.ImportStatePersist` flag](https://github.com/hashicorp/terraform-plugin-sdk/issues/717) with an existing active connection enables the manipulation of that connection to be tested via the acceptance testing framework, but at the end of the `TestCase` all resources in the Terraform state created during the test are destroyed and destroying the active connection is not at all desirable given the overhead in getting the connection into the active state.

### Attempted Solutions

Each `TestStep.Check` function is passed a `*terraform.State` object, so I tried deleting the resource from this object. However this in-memory state is never persisted and is local to each individual `TestStep`.

### Proposal

Add a new `TestStep` field that indicates to the acceptance testing framework that a resource (or list of resources) is not to be deleted at the end of the `TestCase`.

### References

Upstream Terraform CLI issue for configuration language support of a similar facility: https://github.com/hashicorp/terraform/issues/3874.

**Comment by vmanilo** [comment]
hey guys 👋 

I have one recent use-case with testing resource logic, which requires to import existing resource to the acc test flow,  then I'm trying to modify it and checking the error message. Due to backend logic I can't create such resource type directly from terraform, but as this resources existing in the system, potentially user may be able to import this resource to the terraform and then try to modify it.
That's why I was looking for how to setup test in the way that I can import resource, but when test finished - prevent it from destroying.

Please take a look at this test https://github.com/Twingate/terraform-provider-twingate/pull/286/files#diff-520bbd3087681ff4b701d292654e17eb48c163fd43a3cf1f87994fcef3614817

**Comment by austinvalle** [comment]
Bubbling up this info from the recent closed PR:

> In the near/medium term (current forecast looks like `1.7`, so later this year), [terraform](https://github.com/hashicorp/terraform) will support the ability to unmanage resources (e.g. the equivalent of `state rm`) by putting something in the configuration and it’ll be part of the plan like everything else, similar to the [import block](https://developer.hashicorp.com/terraform/language/import) introduced in `1.5`. This means it would be feasible to write another `Config` step that applies the state removal without any testing framework changes.

**Comment by bflad** [comment]
Hi folks 👋

To close the loop here, Terraform 1.7 and later do include the ability to unmanage resources via the [`removed` configuration block](https://developer.hashicorp.com/terraform/language/resources/syntax#removing-resources). To utilize this in your acceptance testing, add a `TestStep` with a configuration that does not include the `resource` block of the resource to unmanage but does include the `removed` block with `destroy = false` for that resource.

As a quick example:

```go
[]resource.TestStep{
  {
    Config: `
resource "examplecloud_thing" "test" {}
`,
  },
  // ... potentially other TestStep ...
  {
    Config: `
removed {
  from = examplecloud_thing.test

  lifecycle {
    destroy = false
  }
}
`,
  },
}
```

This will remove the state for the resource, meaning that the implicit destroy ran at the end of the test steps will no longer try to destroy that resource.

If you have your acceptance testing setup to run across many Terraform versions, there is support for [Terraform version checks](https://developer.hashicorp.com/terraform/plugin/testing/acceptance-tests/tfversion-checks), such as `tfversion.SkipBelow(tfversion.Version1_7_0)`, which can prevent testing errors from earlier versions of Terraform which do not support the `removed` block.

Hope this helps!
